#!/usr/bin/env python3
"""Simulate the whole board, from the schematic rather than from a hand deck.

The decks in hardware/totem-v3.5-reference/sim check blocks of the design
that were written out by hand. They verify the arithmetic, but they do not
verify the drawing: a value could change on the sheet and the deck would go
on testing the old one.

This takes the other route. KiCad exports a netlist from the schematic, and
the deck is built from that — every component, every net, with the values
the sheet carries. If the schematic changes, this changes with it.

What can and cannot be proved this way is worth being plain about. The
passive network is real: resistors, capacitors, and the nets between them
come straight off the drawing. The integrated circuits are behavioural
models (see sim/board_models.lib) standing for the load each one presents,
because no vendor publishes a SPICE model for an ESP32 module and what
those parts do is firmware, not circuit behaviour. So this checks that the
power design holds up under the currents those parts draw. It does not
check that an ESP32 boots.

Usage: python3 sim_board.py
"""

import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parents[3]
SCH = HERE / "hardware/totem-v3.5-reference/schematic/totem.kicad_sch"
MODELS = HERE / "hardware/totem-v3.5-reference/sim/board_models.lib"
OUT = HERE / "hardware/totem-v3.5-reference/sim/board.cir"

sys.path.insert(0, str(HERE / "hardware/totem-v3.5-reference/schematic"))
from kicad_sexp import children, head, parse, sval  # noqa: E402

# Which model stands in for which part, by the symbol's library name.
# Pin NUMBERS, because that is what a netlist keys pins by: names belong to
# the symbol, numbers to the package, and a netlist speaks the package.
# Getting this wrong is silent — every lookup misses, every node falls back
# to ground, and the part is shorted out without a word about it.
MODEL = {
    "ESP32-WROOM-32E": ("ESP32", ["2", "1"]),
    "MAX-M10S": ("MAXM10S", ["8", "1"]),
    "ICM-20948": ("ICM20948", ["13", "18", "10"]),
    "TP4056-42-ESOP8": ("TP4056", ["1", "2", "3", "4", "5", "6", "7", "8", "9"]),
    "AP2127K-3.3": ("LDO_3V3", ["1", "2", "3", "4", "5"]),
    "Q_PMOS": ("PMOS_SW", ["G", "S", "D"]),
    "LED": ("LED_IND", ["2", "1"]),
    "Microphone": ("MIC_MEMS", ["1", "2"]),
}
# The two strips differ only in how many pixels hang off them.
RING_MODEL = {"DS1": "WS2812B_RING", "DS61": "WS2812B_CRYSTAL"}


def spice_node(name):
    """A net name SPICE will accept. Ground is node 0, as it must be."""
    if name in ("GND", "/GND"):
        return "0"
    return re.sub(r"[^A-Za-z0-9_]", "_", name.lstrip("/"))


def spice_value(value):
    """A component value SPICE understands: 4k7 and 330R are not its dialect."""
    v = value.strip()
    m = re.fullmatch(r"(\d+)([kKmMRrunpF])(\d+)", v)
    if m:                       # 4k7 -> 4.7k, 1k2 -> 1.2k
        unit = "" if m.group(2) in "Rr" else m.group(2)
        return f"{m.group(1)}.{m.group(3)}{unit}"
    m = re.fullmatch(r"(\d+(?:\.\d+)?)[Rr]", v)
    if m:                       # 330R -> 330
        return m.group(1)
    return v


def netlist():
    """Ask KiCad for the schematic's netlist, and parse it."""
    tmp = HERE / "hardware/totem-v3.5-reference/sim/.netlist.net"
    run = subprocess.run(
        ["kicad-cli", "sch", "export", "netlist", "--format", "kicadsexpr",
         "--output", str(tmp), str(SCH)],
        capture_output=True, text=True, timeout=300,
    )
    if run.returncode != 0 or not tmp.exists():
        raise SystemExit(f"could not export a netlist: {run.stderr.strip()[:300]}")
    tree = parse(tmp.read_text())[0]
    tmp.unlink()

    comps = {}
    for block in children(tree, "components"):
        for comp in children(block, "comp"):
            ref = sval(children(comp, "ref")[0])
            val = children(comp, "value")
            libsrc = children(comp, "libsource")
            name = ""
            if libsrc:
                part = children(libsrc[0], "part")
                name = sval(part[0]) if part else ""
            comps[ref] = {"value": sval(val[0]) if val else "", "part": name, "pins": {}}

    for block in children(tree, "nets"):
        for net in children(block, "net"):
            name = sval(children(net, "name")[0])
            for node in children(net, "node"):
                ref = sval(children(node, "ref")[0])
                pin = sval(children(node, "pin")[0])
                if ref in comps:
                    comps[ref]["pins"][pin] = name
    return comps


def deck(comps):
    """One SPICE deck for the whole board."""
    lines = [
        "* The Totem reference design, built from totem.kicad_sch.",
        "* Generated by sim_board.py — do not edit; edit the schematic.",
        f'.include "{MODELS}"',
        "",
        "* The cable. Swept in the analyses below to cover plugged and not.",
        "VUSB VBUS 0 dc 5.0",
        "* The cell, as a source stiff enough that its own impedance is not",
        "* what is being measured here.",
        "VCELL VBATX 0 dc 4.2",
        "RCELL VBATX VBAT 0.15",
        "",
        "* The power button. 1e12 is released, 1 is held: the gate is what",
        "* decides whether this board is on at all, so both states are run.",
        "RBTN POWER_EN VBAT 1e12",
        "",
    ]
    skipped = []
    for ref in sorted(comps, key=lambda r: (r[0], len(r), r)):
        c = comps[ref]
        pins, part, value = c["pins"], c["part"], c["value"]
        if not pins:
            skipped.append(f"{ref} (no connections)")
            continue

        if ref.startswith("R") and len(pins) == 2:
            a, b = (spice_node(pins[p]) for p in sorted(pins))
            lines.append(f"{ref} {a} {b} {spice_value(value)}")
        elif ref.startswith("C") and len(pins) == 2:
            a, b = (spice_node(pins[p]) for p in sorted(pins))
            lines.append(f"{ref} {a} {b} {spice_value(value)}")
        elif ref in RING_MODEL:
            nodes = [spice_node(pins.get(p, "0")) for p in ("1", "3", "4")]
            lines.append(f"X{ref} {' '.join(nodes)} {RING_MODEL[ref]}")
        elif part in MODEL:
            model, order = MODEL[part]
            nodes = [spice_node(pins.get(p, "0")) for p in order]
            lines.append(f"X{ref} {' '.join(nodes)} {model}")
        else:
            # Connectors, switches, pads: open circuits, one stub per pin.
            ns = [spice_node(v) for v in pins.values()]
            stub = {1: "STUB1", 2: "STUB2", 3: "STUB3"}.get(len(set(ns)))
            if stub:
                lines.append(f"X{ref} {' '.join(sorted(set(ns)))} {stub}")
            else:
                for i, n in enumerate(sorted(set(ns))):
                    lines.append(f"R{ref}_{i} {n} 0 1e12")
    # A net that only one thing touches has nothing to solve against, and
    # ngspice says so as a singular matrix rather than as a net name. Tie
    # each one to ground through an open circuit's worth of resistance.
    seen = {}
    for ln in lines:
        if ln.startswith(("*", ".", "V", "R", "X")) and " " in ln:
            for tok in ln.split()[1:]:
                if re.fullmatch(r"[A-Za-z0-9_]+", tok) and not re.fullmatch(r"[\d.]+[a-zA-Z]?", tok):
                    seen[tok] = seen.get(tok, 0) + 1
    for node, n in sorted(seen.items()):
        if n == 1 and node != "0":
            lines.append(f"RFLOAT_{node} {node} 0 1e12")
    return lines, skipped


ANALYSES = """
.control
  set noaskquit

  * --- 1. Button released. The board must be off. -------------------
  op
  let offr = v(_3v3)
  echo RESULT off_rail = $&offr

  * --- 2. Normal use, button held. -----------------------------------
  * The firmware lights north and the peers, not the whole ring: about
  * sixteen pixels, which is 576 mA rather than 2.16 A. The radio is at
  * its transmit peak, which is the worst moment for the rail.
  alter RBTN = 1
  alter @i.xds1.iring[dc] = 0.576
  dc VCELL 3.35 4.25 0.05
  let nmin = minimum(v(_3v3))
  echo RESULT normal_rail_min = $&nmin
  let nmax = maximum(v(_3v3))
  echo RESULT normal_rail_max = $&nmax
  alter VCELL dc = 4.2
  op
  let ncur = -i(vcell)
  echo RESULT normal_cell_current = $&ncur
  let nvb = v(vbat)
  echo RESULT normal_vbat = $&nvb
  let vbs = v(vbat_sense)
  echo RESULT vbat_sense = $&vbs
  let vus = v(vbus_sense)
  echo RESULT vbus_sense = $&vus

  * --- 3. Cable out. The rail must hold on the cell alone. -----------
  alter VUSB dc = 0
  op
  let nur = v(_3v3)
  echo RESULT no_usb_rail = $&nur
  alter VUSB dc = 5.0

  * --- 4. The whole ring at full white, which the firmware never does.
  alter @i.xds1.iring[dc] = 2.16
  dc VCELL 3.35 4.25 0.05
  let fmin = minimum(v(_3v3))
  echo RESULT full_white_rail_min = $&fmin
  alter VCELL dc = 4.2
  op
  let fcur = -i(vcell)
  echo RESULT full_white_current = $&fcur

  * --- 5. Charging a flat cell, board asleep. ------------------------
  alter @i.xds1.iring[dc] = 0
  alter @i.xu1.ipeak[dc] = 0.05
  alter VCELL dc = 3.6
  op
  let chg = i(vcell)
  echo RESULT charge_current = $&chg
  quit
.endc
.end
"""


def main():
    comps = netlist()
    lines, skipped = deck(comps)
    OUT.write_text("\n".join(lines) + "\n" + ANALYSES)

    print(f"{len(comps)} components from the schematic -> {OUT.name}")
    for s in skipped:
        print(f"  skipped: {s}")

    run = subprocess.run(["ngspice", "-b", str(OUT)],
                         capture_output=True, text=True, timeout=300)
    out = run.stdout + run.stderr
    got = {m.group(1): float(m.group(2))
           for m in re.finditer(r"RESULT (\w+) = ([-\d.e+]+)", out)}

    # (name, comparison, limit, what it means)
    checks = [
        ("off_rail", "<=", 0.10,
         "button released: the rail is down, so the power gate holds the board off"),
        ("normal_rail_min", ">=", 3.00,
         "normal use, worst cell: the rail stays above the ESP32's minimum"),
        ("normal_rail_max", ">=", 3.29,
         "full cell: the regulator is in regulation"),
        ("no_usb_rail", ">=", 3.00,
         "cable out: the board runs from the cell alone"),
        ("vbat_sense", "<=", 2.45,
         "the cell divider stays inside the ADC's window"),
        ("vbus_sense", ">=", 2.475,
         "VBUS presence clears the logic threshold"),
        ("vbus_sense", "<=", 3.60,
         "and stays under the ESP32's absolute maximum"),
        ("full_white_rail_min", ">=", 3.00,
         "XFAIL: every pixel at full white collapses the rail. The firmware "
         "never lights the ring this way, and this records the ceiling"),
    ]
    ops = {"<=": lambda a, b: a <= b, ">=": lambda a, b: a >= b}

    print()
    failed = expected = 0
    for name, op, limit, why in checks:
        xfail = why.startswith("XFAIL:")
        if name not in got:
            print(f"  MISSING {name}: the simulation did not report it")
            failed += 1
            continue
        ok = ops[op](got[name], limit)
        if ok and not xfail:
            print(f"  pass  {name:<20} {got[name]:>9.3f} {op} {limit:<6} {why}")
        elif not ok and xfail:
            print(f"  known {name:<20} {got[name]:>9.3f} {op} {limit}")
            print(f"        {why[6:].strip()}")
            expected += 1
        elif ok and xfail:
            print(f"  FIXED {name}: expected to fail and did not — update the note")
            failed += 1
        else:
            print(f"  FAIL  {name:<20} {got[name]:>9.3f} {op} {limit:<6} {why}")
            failed += 1

    for name in ("normal_cell_current", "full_white_current", "normal_vbat"):
        if name in got:
            print(f"  ----  {name:<20} {got[name]:>9.3f}")

    print(f"\n{len(checks) - failed - expected} passed, {failed} failed, "
          f"{expected} known limits recorded")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
