from collections import defaultdict
from skidl import Pin, Part, Alias, SchLib, SKIDL, TEMPLATE

from skidl.pin import pin_types

SKIDL_lib_version = '0.0.1'

totem = SchLib(tool=SKIDL).add_parts(*[
        Part(**{ 'name':'ESP32-WROOM-32E', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ESP32-WROOM-32E'}), 'ref_prefix':'U', 'fplist':['RF_Module:ESP32-WROOM-32E'], 'footprint':'RF_Module:ESP32-WROOM-32E', 'keywords':'RF Radio BT ESP ESP32 Espressif onboard PCB antenna', 'description':'RF Module, ESP32-D0WD-V3 SoC, without PSRAM, Wi-Fi 802.11b/g/n, Bluetooth, BLE, 32-bit, 2.7-3.6V, onboard antenna, SMD', 'datasheet':'https://www.espressif.com/sites/default/files/documentation/esp32-wroom-32e_esp32-wroom-32ue_datasheet_en.pdf', 'pins':[
            Pin(num='2',name='VDD',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='EN',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='SENSOR_VP',func=pin_types.INPUT,unit=1),
            Pin(num='5',name='SENSOR_VN',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='IO34',func=pin_types.INPUT,unit=1),
            Pin(num='7',name='IO35',func=pin_types.INPUT,unit=1),
            Pin(num='8',name='IO32',func=pin_types.BIDIR,unit=1),
            Pin(num='9',name='IO33',func=pin_types.BIDIR,unit=1),
            Pin(num='10',name='IO25',func=pin_types.BIDIR,unit=1),
            Pin(num='11',name='IO26',func=pin_types.BIDIR,unit=1),
            Pin(num='12',name='IO27',func=pin_types.BIDIR,unit=1),
            Pin(num='13',name='IO14',func=pin_types.BIDIR,unit=1),
            Pin(num='14',name='IO12',func=pin_types.BIDIR,unit=1),
            Pin(num='16',name='IO13',func=pin_types.BIDIR,unit=1),
            Pin(num='17',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='18',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='19',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='20',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='21',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='22',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='23',name='IO15',func=pin_types.BIDIR,unit=1),
            Pin(num='24',name='IO2',func=pin_types.BIDIR,unit=1),
            Pin(num='25',name='IO0',func=pin_types.BIDIR,unit=1),
            Pin(num='26',name='IO4',func=pin_types.BIDIR,unit=1),
            Pin(num='27',name='IO16',func=pin_types.BIDIR,unit=1),
            Pin(num='28',name='IO17',func=pin_types.BIDIR,unit=1),
            Pin(num='29',name='IO5',func=pin_types.BIDIR,unit=1),
            Pin(num='30',name='IO18',func=pin_types.BIDIR,unit=1),
            Pin(num='31',name='IO19',func=pin_types.BIDIR,unit=1),
            Pin(num='32',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='33',name='IO21',func=pin_types.BIDIR,unit=1),
            Pin(num='34',name='RXD0/IO3',func=pin_types.BIDIR,unit=1),
            Pin(num='35',name='TXD0/IO1',func=pin_types.BIDIR,unit=1),
            Pin(num='36',name='IO22',func=pin_types.BIDIR,unit=1),
            Pin(num='37',name='IO23',func=pin_types.BIDIR,unit=1),
            Pin(num='[1,15,38,39]',name='GND',func=pin_types.PWRIN,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'MAX-M10S', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'MAX-M10S'}), 'ref_prefix':'U', 'fplist':['RF_GPS:ublox_MAX'], 'footprint':'RF_GPS:ublox_MAX', 'keywords':'ublox GPS GNSS module', 'description':'GNSS Module MAX M10, VCC 1.65V to 3.6V', 'datasheet':'https://content.u-blox.com/sites/default/files/MAX-M10S_DataSheet_UBX-20035208.pdf', 'pins':[
            Pin(num='1',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='TXD',func=pin_types.OUTPUT,unit=1),
            Pin(num='3',name='RXD',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='TIMEPULSE',func=pin_types.OUTPUT,unit=1),
            Pin(num='5',name='EXTINT',func=pin_types.INPUT,unit=1),
            Pin(num='6',name='V_BCKP',func=pin_types.PWRIN,unit=1),
            Pin(num='7',name='VCC_IO',func=pin_types.PWRIN,unit=1),
            Pin(num='8',name='VCC',func=pin_types.PWRIN,unit=1),
            Pin(num='9',name='~{RESET}',func=pin_types.INPUT,unit=1),
            Pin(num='10',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='11',name='RF_IN',func=pin_types.INPUT,unit=1),
            Pin(num='12',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='13',name='LNA_EN',func=pin_types.OUTPUT,unit=1),
            Pin(num='14',name='VCC_RF',func=pin_types.PWROUT,unit=1),
            Pin(num='15',name='VIO_SEL',func=pin_types.INPUT,unit=1),
            Pin(num='16',name='SDA',func=pin_types.BIDIR,unit=1),
            Pin(num='17',name='SCL',func=pin_types.INPUT,unit=1),
            Pin(num='18',name='~{SAFEBOOT}',func=pin_types.INPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'TP4056', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'TP4056'}), 'ref_prefix':'U', 'fplist':None, 'footprint':None, 'keywords':None, 'description':'', 'datasheet':None, 'pins':[
            Pin(num='1',name='TEMP',func=pin_types.INPUT),
            Pin(num='2',name='PROG',func=pin_types.PASSIVE),
            Pin(num='3',name='GND',func=pin_types.PWRIN),
            Pin(num='4',name='VCC',func=pin_types.PWRIN),
            Pin(num='5',name='BAT',func=pin_types.PWROUT),
            Pin(num='6',name='BAT2',func=pin_types.PASSIVE),
            Pin(num='7',name='CHRG',func=pin_types.OPENCOLL),
            Pin(num='8',name='STDBY',func=pin_types.OPENCOLL)] }),
        Part(**{ 'name':'AP2127K-3.3', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'AP2127K-3.3'}), 'ref_prefix':'U', 'fplist':['Package_TO_SOT_SMD:SOT-23-5', 'Package_TO_SOT_SMD:SOT-23-5'], 'footprint':'Package_TO_SOT_SMD:SOT-23-5', 'keywords':'linear regulator ldo fixed positive', 'description':'300mA low dropout linear regulator, shutdown pin, 2.5V-6V input voltage, 3.3V fixed positive output, SOT-23-5', 'datasheet':'https://www.diodes.com/assets/Datasheets/AP2127.pdf', 'pins':[
            Pin(num='1',name='VIN',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='3',name='EN',func=pin_types.INPUT,unit=1),
            Pin(num='4',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='5',name='VOUT',func=pin_types.PWROUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'ICM-20948', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'ICM-20948'}), 'ref_prefix':'U', 'fplist':['Sensor_Motion:InvenSense_QFN-24_3x3mm_P0.4mm'], 'footprint':'Sensor_Motion:InvenSense_QFN-24_3x3mm_P0.4mm', 'keywords':'mems magnetometer', 'description':'InvenSense 9-Axis Motion Sensor, Accelerometer, Gyroscope, Compass, I2C/SPI, QFN-24', 'datasheet':'http://www.invensense.com/wp-content/uploads/2016/06/DS-000189-ICM-20948-v1.3.pdf', 'pins':[
            Pin(num='1',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='2',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='3',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='4',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='5',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='6',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='7',name='AUX_CL',func=pin_types.OUTPUT,unit=1),
            Pin(num='8',name='VDDIO',func=pin_types.PWRIN,unit=1),
            Pin(num='9',name='SDO/AD0',func=pin_types.BIDIR,unit=1),
            Pin(num='10',name='REGOUT',func=pin_types.PASSIVE,unit=1),
            Pin(num='11',name='FSYNC',func=pin_types.INPUT,unit=1),
            Pin(num='12',name='INT1',func=pin_types.OUTPUT,unit=1),
            Pin(num='13',name='VDD',func=pin_types.PWRIN,unit=1),
            Pin(num='14',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='15',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='16',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='17',name='NC',func=pin_types.NOCONNECT,unit=1),
            Pin(num='18',name='GND',func=pin_types.PWRIN,unit=1),
            Pin(num='19',name='RESV',func=pin_types.NOCONNECT,unit=1),
            Pin(num='20',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='21',name='AUX_DA',func=pin_types.BIDIR,unit=1),
            Pin(num='22',name='~{CS}',func=pin_types.INPUT,unit=1),
            Pin(num='23',name='SCL/SCLK',func=pin_types.INPUT,unit=1),
            Pin(num='24',name='SDA/SDI',func=pin_types.BIDIR,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'WS2812B', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'WS2812B'}), 'ref_prefix':'D', 'fplist':['LED_SMD:LED_WS2812B_PLCC4_5.0x5.0mm_P3.2mm'], 'footprint':'LED_SMD:LED_WS2812B_PLCC4_5.0x5.0mm_P3.2mm', 'keywords':'RGB LED NeoPixel addressable', 'description':'RGB LED with integrated controller', 'datasheet':'https://cdn-shop.adafruit.com/datasheets/WS2812B.pdf', 'pins':[
            Pin(num='1',name='VDD',func=pin_types.PWRIN,unit=1),
            Pin(num='2',name='DOUT',func=pin_types.OUTPUT,unit=1),
            Pin(num='3',name='VSS',func=pin_types.PWRIN,unit=1),
            Pin(num='4',name='DIN',func=pin_types.INPUT,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'LED', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'LED'}), 'ref_prefix':'D', 'fplist':[''], 'footprint':'', 'keywords':'LED diode', 'description':'Light emitting diode', 'datasheet':'', 'pins':[
            Pin(num='1',name='K',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='A',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Q_PMOS', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Q_PMOS'}), 'ref_prefix':'Q', 'fplist':[''], 'footprint':'', 'keywords':'PMOS P-MOS', 'description':'P-MOSFET transistor', 'datasheet':'', 'pins':[
            Pin(num='D',name='D',func=pin_types.PASSIVE,unit=1),
            Pin(num='G',name='G',func=pin_types.INPUT,unit=1),
            Pin(num='S',name='S',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'USB_C_Receptacle_USB2.0_16P', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'USB_C_Receptacle_USB2.0_16P'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'', 'keywords':'usb universal serial bus type-C USB2.0', 'description':'USB 2.0-only 16P Type-C Receptacle connector', 'datasheet':'https://www.usb.org/sites/default/files/documents/usb_type-c.zip', 'pins':[
            Pin(num='A1',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='A4',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='A5',name='CC1',func=pin_types.BIDIR,unit=1),
            Pin(num='A6',name='D+',func=pin_types.BIDIR,unit=1),
            Pin(num='A7',name='D-',func=pin_types.BIDIR,unit=1),
            Pin(num='A8',name='SBU1',func=pin_types.BIDIR,unit=1),
            Pin(num='A9',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='A12',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='B1',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='B4',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='B5',name='CC2',func=pin_types.BIDIR,unit=1),
            Pin(num='B6',name='D+',func=pin_types.BIDIR,unit=1),
            Pin(num='B7',name='D-',func=pin_types.BIDIR,unit=1),
            Pin(num='B8',name='SBU2',func=pin_types.BIDIR,unit=1),
            Pin(num='B9',name='VBUS',func=pin_types.PASSIVE,unit=1),
            Pin(num='B12',name='GND',func=pin_types.PASSIVE,unit=1),
            Pin(num='SH',name='SHIELD',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x02', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x02'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'', 'keywords':'connector', 'description':'Generic connector, single row, 01x02, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='Pin_2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'Conn_01x01', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Conn_01x01'}), 'ref_prefix':'J', 'fplist':[''], 'footprint':'', 'keywords':'connector', 'description':'Generic connector, single row, 01x01, script generated (kicad-library-utils/schlib/autogen/connector/)', 'datasheet':'', 'pins':[
            Pin(num='1',name='Pin_1',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'SW_Push', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'SW_Push'}), 'ref_prefix':'SW', 'fplist':[''], 'footprint':'', 'keywords':'switch normally-open pushbutton push-button', 'description':'Push button switch, generic, two pins', 'datasheet':'', 'pins':[
            Pin(num='1',name='1',func=pin_types.PASSIVE),
            Pin(num='2',name='2',func=pin_types.PASSIVE)], 'unit_defs':[] }),
        Part(**{ 'name':'Microphone', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'Microphone'}), 'ref_prefix':'MK', 'fplist':[''], 'footprint':'', 'keywords':'microphone', 'description':'Microphone', 'datasheet':'', 'pins':[
            Pin(num='1',name='-',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',name='+',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'R', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'R'}), 'ref_prefix':'R', 'fplist':[''], 'footprint':'', 'keywords':'R res resistor', 'description':'Resistor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] }),
        Part(**{ 'name':'C', 'dest':TEMPLATE, 'tool':SKIDL, 'aliases':Alias({'C'}), 'ref_prefix':'C', 'fplist':[''], 'footprint':'', 'keywords':'cap capacitor', 'description':'Unpolarized capacitor', 'datasheet':'', 'pins':[
            Pin(num='1',func=pin_types.PASSIVE,unit=1),
            Pin(num='2',func=pin_types.PASSIVE,unit=1)], 'unit_defs':[] })])